'use client';
import { useState } from 'react';
import { FileText, Download, Edit, ChevronRight, ChevronLeft, Check, AlertTriangle, Copy, Loader2 } from 'lucide-react';
import { useLanguage } from '@/lib/language-context';
import { t } from '@/lib/translations';
import { saveDocumentDraft } from '@/lib/session';

interface RTIFormData {
  applicantName: string;
  applicantAddress: string;
  applicantPhone: string;
  applicantEmail: string;
  department: string;
  informationSought: string;
}

const INITIAL_DATA: RTIFormData = {
  applicantName: '',
  applicantAddress: '',
  applicantPhone: '',
  applicantEmail: '',
  department: '',
  informationSought: '',
};

const COMMON_DEPARTMENTS = [
  'Municipal Corporation / Nagar Palika',
  'District Collector Office',
  'Police Department',
  'Public Works Department (PWD)',
  'Revenue Department',
  'Education Department',
  'Health Department',
  'Water Supply Department',
  'Electricity Distribution Company',
  'Food & Civil Supplies Department',
  'Labour Department',
  'Income Tax Department',
  'Passport Office',
  'Regional Transport Office (RTO)',
];

export default function RTIPage() {
  const { language } = useLanguage();
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<RTIFormData>(INITIAL_DATA);
  const [generatedText, setGeneratedText] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  const totalSteps = 3;

  const update = (field: keyof RTIFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const canProceed = () => {
    if (step === 1) return formData.applicantName && formData.applicantAddress && formData.applicantPhone;
    if (step === 2) return formData.department && formData.informationSought;
    return true;
  };

  const generateApplication = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/rti-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...formData, language }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setGeneratedText(data.application);
      // Persist to session for dashboard history
      saveDocumentDraft({
        type: 'rti',
        title: `RTI to ${formData.department || 'Government Department'}`,
        department: formData.department,
        language: language as 'en' | 'hi' | 'mr',
        preview: data.application.slice(0, 120),
      });
      setStep(3);
    } catch (err) {
      setError(err instanceof Error ? err.message : t(language, 'processingError'));
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = async () => {
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });

    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - 2 * margin;

    // Header
    doc.setFillColor(255, 153, 51);
    doc.rect(0, 0, pageWidth, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('NyayaSathi - RTI Application', margin, 10);
    doc.text('www.nyaysathi.in', pageWidth - margin, 10, { align: 'right' });

    // Content
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(generatedText, maxWidth);
    let y = 25;
    const lineHeight = 6;
    const pageHeight = doc.internal.pageSize.getHeight() - 20;

    for (const line of lines) {
      if (y > pageHeight) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += lineHeight;
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by NyayaSathi | General information only, not legal advice. | NALSA: 15100', margin, doc.internal.pageSize.getHeight() - 8);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, doc.internal.pageSize.getHeight() - 8, { align: 'right' });
    }

    const fileName = `RTI_Application_${formData.applicantName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  };

  const copyText = async () => {
    await navigator.clipboard.writeText(generatedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-3">
          <div
            className="w-10 h-10 rounded-lg flex items-center justify-center"
            style={{ background: '#1d4ed8' }}
          >
            <FileText className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="font-bold text-gray-900 text-xl">{t(language, 'rtiTitle')}</h1>
            <p className="text-gray-500 text-sm">{t(language, 'rtiSubtitle')}</p>
          </div>
        </div>

        {/* Progress */}
        <div className="flex items-center gap-2 mt-4">
          {[1, 2, 3].map(s => (
            <div key={s} className="flex items-center gap-2">
              <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold transition-all border ${
                step >= s
                  ? 'bg-blue-700 text-white border-blue-700'
                  : 'bg-white text-gray-300 border-gray-200'
              }`}>
                {step > s ? <Check className="w-4 h-4" /> : s}
              </div>
              {s < 3 && <div className={`h-0.5 w-12 sm:w-20 rounded transition-all ${step > s ? 'bg-blue-700' : 'bg-gray-200'}`} />}
            </div>
          ))}
          <span className="ml-2 text-gray-400 text-xs">
            {t(language, 'step')} {step} {t(language, 'of')} {totalSteps}
          </span>
        </div>
      </div>

      {/* Step Labels */}
      <div className="grid grid-cols-3 gap-2 mb-6 text-center">
        {[t(language, 'yourDetails'), t(language, 'informationDetails'), t(language, 'review')].map((label, i) => (
          <div key={i} className={`text-xs font-medium ${
            step === i + 1 ? 'text-blue-700' : step > i + 1 ? 'text-gray-400' : 'text-gray-300'
          }`}>
            {label}
          </div>
        ))}
      </div>

      {/* Disclaimer */}
      <div className="alert-warning mb-6">
        <AlertTriangle className="w-4 h-4 text-amber-600 flex-shrink-0 mt-0.5" />
        <p>{t(language, 'disclaimer')}</p>
      </div>

      {/* Step 1: Personal Details */}
      {step === 1 && (
        <div className="card p-6 space-y-4">
          <h2 className="font-semibold text-gray-900 mb-4">{t(language, 'yourDetails')}</h2>
          <div>
            <label className="label">{t(language, 'name')} *</label>
            <input
              type="text"
              value={formData.applicantName}
              onChange={e => update('applicantName', e.target.value)}
              className="input-field"
              placeholder={language === 'mr' ? 'उदा. राहुल शर्मा' : language === 'hi' ? 'जैसे: राहुल शर्मा' : 'e.g. Rahul Sharma'}
            />
          </div>
          <div>
            <label className="label">{t(language, 'address')} *</label>
            <textarea
              value={formData.applicantAddress}
              onChange={e => update('applicantAddress', e.target.value)}
              className="textarea-field"
              rows={3}
              placeholder={language === 'mr' ? 'संपूर्ण पत्ता, जिल्हा, राज्य, पिन कोड' : language === 'hi' ? 'पूरा पता, जिला, राज्य, पिन कोड' : 'Full address, district, state, PIN code'}
            />
          </div>
          <div>
            <label className="label">{t(language, 'phone')} *</label>
            <input
              type="tel"
              value={formData.applicantPhone}
              onChange={e => update('applicantPhone', e.target.value)}
              className="input-field"
              placeholder="+91 98765 43210"
            />
          </div>
          <div>
            <label className="label">{t(language, 'email')}</label>
            <input
              type="email"
              value={formData.applicantEmail}
              onChange={e => update('applicantEmail', e.target.value)}
              className="input-field"
              placeholder="email@example.com"
            />
          </div>
        </div>
      )}

      {/* Step 2: Information Details */}
      {step === 2 && (
        <div className="card p-6 space-y-4">
          <h2 className="font-semibold text-gray-900 mb-4">{t(language, 'informationDetails')}</h2>
          <div>
            <label className="label">{t(language, 'department')} *</label>
            <input
              type="text"
              value={formData.department}
              onChange={e => update('department', e.target.value)}
              className="input-field mb-2"
              placeholder={language === 'mr' ? 'विभागाचे नाव' : language === 'hi' ? 'विभाग का नाम' : 'Department name'}
            />
            <div className="flex flex-wrap gap-1.5 mt-2">
              {COMMON_DEPARTMENTS.map(dept => (
                <button
                  key={dept}
                  onClick={() => update('department', dept)}
                  className={`text-xs px-2.5 py-1 rounded border transition-all ${
                    formData.department === dept
                      ? 'bg-blue-50 border-blue-300 text-blue-700'
                      : 'bg-white border-gray-200 text-gray-500 hover:border-gray-400 hover:text-gray-700'
                  }`}
                >
                  {dept}
                </button>
              ))}
            </div>
          </div>
          <div>
            <label className="label">{t(language, 'informationSought')} *</label>
            <textarea
              value={formData.informationSought}
              onChange={e => update('informationSought', e.target.value)}
              className="textarea-field"
              rows={6}
              placeholder={
                language === 'mr'
                  ? 'आपल्याला नेमकी कोणती माहिती हवी आहे ते स्पष्टपणे लिहा. उदा:\n1. आमच्या वार्डातील रस्ते दुरुस्तीसाठी किती निधी मंजूर झाला?\n2. निधी कधी मंजूर झाला आणि किती खर्च झाला?'
                  : language === 'hi'
                  ? 'आप जो जानकारी चाहते हैं उसे स्पष्ट रूप से लिखें। जैसे:\n1. हमारे वार्ड में सड़क मरम्मत के लिए कितना बजट मंजूर हुआ?\n2. बजट कब मंजूर हुआ और अब तक कितना खर्च हुआ?'
                  : 'Clearly describe the information you need. e.g:\n1. What is the approved budget for road repairs in our ward?\n2. When was it approved and how much has been spent?'
              }
            />
            <p className="text-gray-400 text-xs mt-1">
              {language === 'mr' ? '💡 जितके विशिष्ट प्रश्न तितकी चांगली उत्तरे मिळतात' : language === 'hi' ? '💡 जितने विशिष्ट सवाल, उतना अच्छा जवाब' : '💡 Tip: More specific questions get better responses'}
            </p>
          </div>
        </div>
      )}

      {/* Step 3: Preview */}
      {step === 3 && (
        <div className="space-y-4">
          {loading && (
            <div className="card p-12 text-center">
              <Loader2 className="w-8 h-8 text-blue-600 animate-spin mx-auto mb-3" />
              <p className="text-gray-500">{t(language, 'generating')}</p>
            </div>
          )}
          {error && (
            <div className="alert-error">
              <AlertTriangle className="w-4 h-4 flex-shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}
          {generatedText && !loading && (
            <div className="card p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="font-semibold text-gray-900">
                  {language === 'mr' ? 'तयार RTI अर्ज' : language === 'hi' ? 'तैयार RTI आवेदन' : 'Generated RTI Application'}
                </h2>
                <div className="flex gap-2">
                  <button
                    onClick={copyText}
                    className="btn-ghost flex items-center gap-1.5 text-xs"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                    {copied ? t(language, 'copied') : t(language, 'copyText')}
                  </button>
                  <button
                    onClick={() => setIsEditing(!isEditing)}
                    className="btn-ghost flex items-center gap-1.5 text-xs"
                  >
                    <Edit className="w-3.5 h-3.5" />
                    {t(language, 'edit')}
                  </button>
                </div>
              </div>

              {isEditing ? (
                <textarea
                  value={generatedText}
                  onChange={e => setGeneratedText(e.target.value)}
                  className="textarea-field font-mono text-sm w-full"
                  rows={20}
                />
              ) : (
                <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 leading-relaxed bg-gray-50 p-4 rounded-lg border border-gray-200 max-h-96 overflow-y-auto">
                  {generatedText}
                </pre>
              )}

              <div className="mt-4 alert-info">
                <p>
                  {language === 'mr'
                    ? '📋 हा अर्ज प्रिंट करून PIО ला पाठवा. केंद्र सरकार विभागासाठी rtionline.gov.in वर ऑनलाइन देखील दाखल करा. ₹10 IPO किंवा DD सोबत जोडा.'
                    : language === 'hi'
                    ? '📋 इस आवेदन को प्रिंट करके PIO को भेजें। केंद्र सरकार विभाग के लिए rtionline.gov.in पर ऑनलाइन भी दाखिल करें। ₹10 IPO या DD संलग्न करें।'
                    : '📋 Print this application and send it to the PIO. For Central Govt departments, also file online at rtionline.gov.in. Attach ₹10 IPO or Demand Draft.'}
                </p>
              </div>

              <div className="mt-4 flex gap-3">
                <button onClick={downloadPDF} className="btn-primary flex items-center gap-2">
                  <Download className="w-4 h-4" />
                  {t(language, 'download')}
                </button>
                <button onClick={() => { setStep(1); setGeneratedText(''); setFormData(INITIAL_DATA); }} className="btn-secondary">
                  {language === 'mr' ? 'नवीन अर्ज' : language === 'hi' ? 'नया आवेदन' : 'New Application'}
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* Navigation */}
      {step < 3 && (
        <div className="flex justify-between mt-6">
          <button
            onClick={() => setStep(s => s - 1)}
            disabled={step === 1}
            className="btn-secondary flex items-center gap-2 disabled:opacity-30"
          >
            <ChevronLeft className="w-4 h-4" />
            {t(language, 'back')}
          </button>
          {step === 2 ? (
            <button
              onClick={generateApplication}
              disabled={!canProceed() || loading}
              className="btn-primary flex items-center gap-2"
            >
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
              {loading ? t(language, 'generating') : t(language, 'generate')}
            </button>
          ) : (
            <button
              onClick={() => setStep(s => s + 1)}
              disabled={!canProceed()}
              className="btn-primary flex items-center gap-2"
            >
              {t(language, 'next')}
              <ChevronRight className="w-4 h-4" />
            </button>
          )}
        </div>
      )}

      {/* RTI Info Cards */}
      {step === 1 && (
        <div className="mt-8 grid sm:grid-cols-3 gap-3">
          {[
            { label: language === 'mr' ? '📅 उत्तर मिळण्याचा कालावधी' : language === 'hi' ? '📅 उत्तर मिलने की अवधि' : '📅 Response Time', value: '30 days' },
            { label: language === 'mr' ? '💰 फी' : language === 'hi' ? '💰 शुल्क' : '💰 Filing Fee', value: '₹10 only' },
            { label: language === 'mr' ? '🏛️ अपील' : language === 'hi' ? '🏛️ अपील' : '🏛️ Appeal', value: '30 days more' },
          ].map(({ label, value }) => (
            <div key={label} className="card p-4 text-center">
              <p className="text-xs text-gray-500 mb-1">{label}</p>
              <p className="font-bold text-blue-700">{value}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
